# Generated by Django 2.1.5 on 2019-01-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userdriven_composition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='sensor_value',
        ),
    ]
