# Generated by Django 2.1.7 on 2019-03-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdriven_composition', '0003_auto_20190121_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_id', models.CharField(max_length=100)),
                ('api_link', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='actuator',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
