# Generated by Django 2.1.5 on 2019-01-21 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userdriven_composition', '0002_remove_actuator_sensor_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='status',
        ),
        migrations.AddField(
            model_name='actuator',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='actuator',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='actuator',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lowersensor',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='lowersensor',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lowersensor',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lowersensor',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
